services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: ${TARGET:-dev}
    image: silmaralberti/rinha-frankenphp:latest
    restart: unless-stopped
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp

  database:
    image: postgres:16-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.93"
          memory: "190MB"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: "rinha"
      POSTGRES_PASSWORD: "rinha-2024"
      POSTGRES_DB: "rinha"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - ./docker/postgresql/postgres.conf:/etc/postgresql.conf:ro
      - ./docker/postgresql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      
volumes:
  pgdata:
