version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: prod
    restart: unless-stopped
    volumes:
      - .:/application
    extra_hosts:
      - host.docker.internal:host-gateway

  ngnix:
    image: nginx:stable-alpine3.17
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/application
    ports:
      - 8000:80

  database:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: "rinha"
      POSTGRES_PASSWORD: "rinha-2024"
      POSTGRES_DB: "rinha"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - ./docker/postgresql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  
volumes:
  pgdata:
    name: rinha-pgdata
